name: Website Checker
on: push

jobs:
    html5-check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
       
            - name: HTML5Validator
              uses: Cyb3r-Jak3/html5validator-action@v7
              with:
                root: .

    lighthouse-check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkou
        
            - name: Lighthouse check
              uses: treosh/lighthouse-ci-action@v12
              with:
                configPath: '.lighthouserc.yml'
                uploadArtifacts: true
